// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vtrpc.proto

package vtrpc // import "vitess.io/vitess/go/vt/proto/vtrpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Code represents canonical error codes. The names, numbers and comments
// must match the ones defined by grpc:
// https://godoc.org/google.golang.org/grpc/codes.
type Code int32

const (
	// OK is returned on success.
	Code_OK Code = 0
	// CANCELED indicates the operation was cancelled (typically by the caller).
	Code_CANCELED Code = 1
	// UNKNOWN error. An example of where this error may be returned is
	// if a Status value received from another address space belongs to
	// an error-space that is not known in this address space. Also
	// errors raised by APIs that do not return enough error information
	// may be converted to this error.
	Code_UNKNOWN Code = 2
	// INVALID_ARGUMENT indicates client specified an invalid argument.
	// Note that this differs from FAILED_PRECONDITION. It indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name).
	Code_INVALID_ARGUMENT Code = 3
	// DEADLINE_EXCEEDED means operation expired before completion.
	// For operations that change the state of the system, this error may be
	// returned even if the operation has completed successfully. For
	// example, a successful response from a server could have been delayed
	// long enough for the deadline to expire.
	Code_DEADLINE_EXCEEDED Code = 4
	// NOT_FOUND means some requested entity (e.g., file or directory) was
	// not found.
	Code_NOT_FOUND Code = 5
	// ALREADY_EXISTS means an attempt to create an entity failed because one
	// already exists.
	Code_ALREADY_EXISTS Code = 6
	// PERMISSION_DENIED indicates the caller does not have permission to
	// execute the specified operation. It must not be used for rejections
	// caused by exhausting some resource (use RESOURCE_EXHAUSTED
	// instead for those errors).  It must not be
	// used if the caller cannot be identified (use Unauthenticated
	// instead for those errors).
	Code_PERMISSION_DENIED Code = 7
	// UNAUTHENTICATED indicates the request does not have valid
	// authentication credentials for the operation.
	Code_UNAUTHENTICATED Code = 16
	// RESOURCE_EXHAUSTED indicates some resource has been exhausted, perhaps
	// a per-user quota, or perhaps the entire file system is out of space.
	Code_RESOURCE_EXHAUSTED Code = 8
	// FAILED_PRECONDITION indicates operation was rejected because the
	// system is not in a state required for the operation's execution.
	// For example, directory to be deleted may be non-empty, an rmdir
	// operation is applied to a non-directory, etc.
	//
	// A litmus test that may help a service implementor in deciding
	// between FAILED_PRECONDITION, ABORTED, and UNAVAILABLE:
	//  (a) Use UNAVAILABLE if the client can retry just the failing call.
	//  (b) Use ABORTED if the client should retry at a higher-level
	//      (e.g., restarting a read-modify-write sequence).
	//  (c) Use FAILED_PRECONDITION if the client should not retry until
	//      the system state has been explicitly fixed.  E.g., if an "rmdir"
	//      fails because the directory is non-empty, FAILED_PRECONDITION
	//      should be returned since the client should not retry unless
	//      they have first fixed up the directory by deleting files from it.
	//  (d) Use FAILED_PRECONDITION if the client performs conditional
	//      REST Get/Update/Delete on a resource and the resource on the
	//      server does not match the condition. E.g., conflicting
	//      read-modify-write on the same resource.
	Code_FAILED_PRECONDITION Code = 9
	// ABORTED indicates the operation was aborted, typically due to a
	// concurrency issue like sequencer check failures, transaction aborts,
	// etc.
	//
	// See litmus test above for deciding between FAILED_PRECONDITION,
	// ABORTED, and UNAVAILABLE.
	Code_ABORTED Code = 10
	// OUT_OF_RANGE means operation was attempted past the valid range.
	// E.g., seeking or reading past end of file.
	//
	// Unlike INVALID_ARGUMENT, this error indicates a problem that may
	// be fixed if the system state changes. For example, a 32-bit file
	// system will generate INVALID_ARGUMENT if asked to read at an
	// offset that is not in the range [0,2^32-1], but it will generate
	// OUT_OF_RANGE if asked to read from an offset past the current
	// file size.
	//
	// There is a fair bit of overlap between FAILED_PRECONDITION and
	// OUT_OF_RANGE.  We recommend using OUT_OF_RANGE (the more specific
	// error) when it applies so that callers who are iterating through
	// a space can easily look for an OUT_OF_RANGE error to detect when
	// they are done.
	Code_OUT_OF_RANGE Code = 11
	// UNIMPLEMENTED indicates operation is not implemented or not
	// supported/enabled in this service.
	Code_UNIMPLEMENTED Code = 12
	// INTERNAL errors. Means some invariants expected by underlying
	// system has been broken.  If you see one of these errors,
	// something is very broken.
	Code_INTERNAL Code = 13
	// UNAVAILABLE indicates the service is currently unavailable.
	// This is a most likely a transient condition and may be corrected
	// by retrying with a backoff.
	//
	// See litmus test above for deciding between FAILED_PRECONDITION,
	// ABORTED, and UNAVAILABLE.
	Code_UNAVAILABLE Code = 14
	// DATA_LOSS indicates unrecoverable data loss or corruption.
	Code_DATA_LOSS Code = 15
)

var Code_name = map[int32]string{
	0:  "OK",
	1:  "CANCELED",
	2:  "UNKNOWN",
	3:  "INVALID_ARGUMENT",
	4:  "DEADLINE_EXCEEDED",
	5:  "NOT_FOUND",
	6:  "ALREADY_EXISTS",
	7:  "PERMISSION_DENIED",
	16: "UNAUTHENTICATED",
	8:  "RESOURCE_EXHAUSTED",
	9:  "FAILED_PRECONDITION",
	10: "ABORTED",
	11: "OUT_OF_RANGE",
	12: "UNIMPLEMENTED",
	13: "INTERNAL",
	14: "UNAVAILABLE",
	15: "DATA_LOSS",
}
var Code_value = map[string]int32{
	"OK":                  0,
	"CANCELED":            1,
	"UNKNOWN":             2,
	"INVALID_ARGUMENT":    3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"UNAUTHENTICATED":     16,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATA_LOSS":           15,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}
func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_vtrpc_b3b3920d8a98a4a3, []int{0}
}

// CallerID is passed along RPCs to identify the originating client
// for a request. It is not meant to be secure, but only
// informational.  The client can put whatever info they want in these
// fields, and they will be trusted by the servers. The fields will
// just be used for logging purposes, and to easily find a client.
// VtGate propagates it to VtTablet, and VtTablet may use this
// information for monitoring purposes, to display on dashboards, or
// for blacklisting purposes.
type CallerID struct {
	// principal is the effective user identifier. It is usually filled in
	// with whoever made the request to the appserver, if the request
	// came from an automated job or another system component.
	// If the request comes directly from the Internet, or if the Vitess client
	// takes action on its own accord, it is okay for this field to be absent.
	Principal string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// component describes the running process of the effective caller.
	// It can for instance be the hostname:port of the servlet initiating the
	// database call, or the container engine ID used by the servlet.
	Component string `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	// subcomponent describes a component inisde the immediate caller which
	// is responsible for generating is request. Suggested values are a
	// servlet name or an API endpoint name.
	Subcomponent         string   `protobuf:"bytes,3,opt,name=subcomponent,proto3" json:"subcomponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallerID) Reset()         { *m = CallerID{} }
func (m *CallerID) String() string { return proto.CompactTextString(m) }
func (*CallerID) ProtoMessage()    {}
func (*CallerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_vtrpc_b3b3920d8a98a4a3, []int{0}
}
func (m *CallerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallerID.Unmarshal(m, b)
}
func (m *CallerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallerID.Marshal(b, m, deterministic)
}
func (dst *CallerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallerID.Merge(dst, src)
}
func (m *CallerID) XXX_Size() int {
	return xxx_messageInfo_CallerID.Size(m)
}
func (m *CallerID) XXX_DiscardUnknown() {
	xxx_messageInfo_CallerID.DiscardUnknown(m)
}

var xxx_messageInfo_CallerID proto.InternalMessageInfo

func (m *CallerID) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *CallerID) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *CallerID) GetSubcomponent() string {
	if m != nil {
		return m.Subcomponent
	}
	return ""
}

// RPCError is an application-level error structure returned by
// VtTablet (and passed along by VtGate if appropriate).
// We use this so the clients don't have to parse the error messages,
// but instead can depend on the value of the code.
type RPCError struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code                 Code     `protobuf:"varint,3,opt,name=code,proto3,enum=vtrpc.Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCError) Reset()         { *m = RPCError{} }
func (m *RPCError) String() string { return proto.CompactTextString(m) }
func (*RPCError) ProtoMessage()    {}
func (*RPCError) Descriptor() ([]byte, []int) {
	return fileDescriptor_vtrpc_b3b3920d8a98a4a3, []int{1}
}
func (m *RPCError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCError.Unmarshal(m, b)
}
func (m *RPCError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCError.Marshal(b, m, deterministic)
}
func (dst *RPCError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCError.Merge(dst, src)
}
func (m *RPCError) XXX_Size() int {
	return xxx_messageInfo_RPCError.Size(m)
}
func (m *RPCError) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCError.DiscardUnknown(m)
}

var xxx_messageInfo_RPCError proto.InternalMessageInfo

func (m *RPCError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RPCError) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_OK
}

func init() {
	proto.RegisterType((*CallerID)(nil), "vtrpc.CallerID")
	proto.RegisterType((*RPCError)(nil), "vtrpc.RPCError")
	proto.RegisterEnum("vtrpc.Code", Code_name, Code_value)
}

func init() { proto.RegisterFile("vtrpc.proto", fileDescriptor_vtrpc_b3b3920d8a98a4a3) }

var fileDescriptor_vtrpc_b3b3920d8a98a4a3 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdd, 0x6e, 0x1a, 0x31,
	0x10, 0x85, 0x0b, 0x21, 0xfc, 0x0c, 0x7f, 0xce, 0xa4, 0x3f, 0x5c, 0x54, 0x6a, 0xc5, 0x55, 0xd5,
	0x0b, 0x90, 0x5a, 0xf5, 0x01, 0xcc, 0x7a, 0x48, 0x5c, 0x96, 0x31, 0xf2, 0xae, 0xd3, 0xb4, 0x37,
	0x2b, 0x42, 0x56, 0x11, 0x15, 0xc1, 0x68, 0xa1, 0x3c, 0x5a, 0x9f, 0xaf, 0xf2, 0x92, 0x36, 0xea,
	0xdd, 0x9e, 0xef, 0x9c, 0x1d, 0xcf, 0x91, 0x0d, 0xed, 0xe3, 0xa1, 0xd8, 0xad, 0x46, 0xbb, 0xc2,
	0x1f, 0x3c, 0x9e, 0x97, 0x62, 0xf8, 0x13, 0x9a, 0xd1, 0x72, 0xb3, 0xc9, 0x0b, 0xad, 0xf0, 0x2d,
	0xb4, 0x76, 0xc5, 0x7a, 0xbb, 0x5a, 0xef, 0x96, 0x9b, 0x41, 0xe5, 0x7d, 0xe5, 0x43, 0xcb, 0x3e,
	0x83, 0xe0, 0xae, 0xfc, 0xe3, 0xce, 0x6f, 0xf3, 0xed, 0x61, 0x50, 0x3d, 0xb9, 0xff, 0x00, 0x0e,
	0xa1, 0xb3, 0xff, 0x75, 0xf7, 0x1c, 0x38, 0x2b, 0x03, 0xff, 0xb1, 0xe1, 0x0c, 0x9a, 0x76, 0x11,
	0x51, 0x51, 0xf8, 0x02, 0x07, 0xd0, 0x78, 0xcc, 0xf7, 0xfb, 0xe5, 0x43, 0xfe, 0x34, 0xeb, 0xaf,
	0xc4, 0x77, 0x50, 0x5b, 0xf9, 0xfb, 0xbc, 0x9c, 0xd0, 0xfb, 0xd4, 0x1e, 0x9d, 0x96, 0x8e, 0xfc,
	0x7d, 0x6e, 0x4b, 0xe3, 0x6b, 0xad, 0x59, 0x11, 0xd5, 0x8f, 0xbf, 0xab, 0x50, 0x0b, 0x10, 0xeb,
	0x50, 0x35, 0x33, 0xf1, 0x02, 0x3b, 0xd0, 0x8c, 0x24, 0x47, 0x14, 0x93, 0x12, 0x15, 0x6c, 0x43,
	0xc3, 0xf1, 0x8c, 0xcd, 0x37, 0x16, 0x55, 0x7c, 0x09, 0x42, 0xf3, 0x8d, 0x8c, 0xb5, 0xca, 0xa4,
	0xbd, 0x72, 0x73, 0xe2, 0x54, 0x9c, 0xe1, 0x2b, 0xb8, 0x50, 0x24, 0x55, 0xac, 0x99, 0x32, 0xba,
	0x8d, 0x88, 0x14, 0x29, 0x51, 0xc3, 0x2e, 0xb4, 0xd8, 0xa4, 0xd9, 0xd4, 0x38, 0x56, 0xe2, 0x1c,
	0x11, 0x7a, 0x32, 0xb6, 0x24, 0xd5, 0xf7, 0x8c, 0x6e, 0x75, 0x92, 0x26, 0xa2, 0x1e, 0xfe, 0x5c,
	0x90, 0x9d, 0xeb, 0x24, 0xd1, 0x86, 0x33, 0x45, 0xac, 0x49, 0x89, 0x06, 0x5e, 0x42, 0xdf, 0xb1,
	0x74, 0xe9, 0x35, 0x71, 0xaa, 0x23, 0x99, 0x92, 0x12, 0x02, 0x5f, 0x03, 0x5a, 0x4a, 0x8c, 0xb3,
	0x51, 0x38, 0xe5, 0x5a, 0xba, 0x24, 0xf0, 0x26, 0xbe, 0x81, 0xcb, 0xa9, 0xd4, 0x31, 0xa9, 0x6c,
	0x61, 0x29, 0x32, 0xac, 0x74, 0xaa, 0x0d, 0x8b, 0x56, 0xd8, 0x5c, 0x4e, 0x8c, 0x0d, 0x29, 0x40,
	0x01, 0x1d, 0xe3, 0xd2, 0xcc, 0x4c, 0x33, 0x2b, 0xf9, 0x8a, 0x44, 0x1b, 0x2f, 0xa0, 0xeb, 0x58,
	0xcf, 0x17, 0x31, 0x85, 0x1a, 0xa4, 0x44, 0x27, 0x34, 0xd7, 0x9c, 0x92, 0x65, 0x19, 0x8b, 0x2e,
	0xf6, 0xa1, 0xed, 0x58, 0xde, 0x48, 0x1d, 0xcb, 0x49, 0x4c, 0xa2, 0x17, 0x0a, 0x29, 0x99, 0xca,
	0x2c, 0x36, 0x49, 0x22, 0xfa, 0x93, 0x2f, 0xd0, 0x5f, 0xfb, 0xd1, 0x71, 0x7d, 0xc8, 0xf7, 0xfb,
	0xd3, 0x5b, 0xf8, 0x31, 0x7c, 0x52, 0x6b, 0x3f, 0x3e, 0x7d, 0x8d, 0x1f, 0xfc, 0xf8, 0x78, 0x18,
	0x97, 0xee, 0xb8, 0xbc, 0x80, 0xbb, 0x7a, 0x29, 0x3e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6b,
	0x9f, 0xeb, 0xc2, 0x45, 0x02, 0x00, 0x00,
}
